sudo: required
services:
 - docker

before_install:
 - docker build -t akys/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true akys/react-test npm test

after_success:
 - docker build -t akystech/multi-client ./client
 - docker build -t akystech/multi-nginx ./nginx
 - docker build -t akystech/multi-server ./server
 - docker build -t akystech/multi-worker ./worker
 # Docker login
 - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push akystech/multi-client
 - docker push akystech/multi-nginx
 - docker push akystech/multi-server
 - docker push akystech/multi-worker