sudo: required
services:
 - docker

before_install:
 - docker build -t akys/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true akys/react-test npm test

after_success:
 - docker build -t akys/multi-client ./client
 - docker build -t akys/multi-nginx ./nginx
 - docker build -t akys/multi-server ./server
 - docker build -t akys/multi-worker ./worker
 # Docker login
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push akys/multi-client
 - docker push akys/multi-nginx
 - docker push akys/multi-server
 - docker push akys/multi-worker